{% set name = "dbus-python" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 991666e498f60dbf3e49b8b7678f5559b8a65034fdf61aae62cdecdb7d89c770

build:
  number: 0
  skip: true  # [win or py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - meson >=0.60.0
    - ninja-base
    - patchelf
  host:
    - pip
    - python
    - meson-python >=0.8.1
    - setuptools
    - wheel
    - dbus
    - glib
  run:
    - dbus
    - python

test:
  imports:
    - dbus
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.freedesktop.org/wiki/Software/DBusBindings/#python
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Python bindings for dbus
  description: |
    D-Bus is a message bus, used for sending messages between applications.
    Conceptually, it fits somewhere in between raw sockets and CORBA in
    terms of complexity.

    This package provides a Python interface to D-Bus.

    See the dbus description for more information about D-Bus in general.
  dev_url: https://gitlab.freedesktop.org/dbus/dbus-python
  doc_url: https://dbus.freedesktop.org/doc/dbus-python

extra:
  recipe-maintainers:
    - duncanmmacleod
